name: Build paho-mqtt library

on:
  push:
    branches:
      - "**"
    paths:
      - "setup/packages/psec/py3-paho-mqtt2"

jobs:
  build-apk:
    runs-on: ubuntu-latest

    container:
      image: alpine:3.21

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          apk update
          apk add alpine-sdk build-base sudo git

      - name: Create abuild user
        run: |
          adduser -D builder
          addgroup builder abuild
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: Set ownership of repo
        run: |
          chown -R builder:builder setup/packages/psec/py3-paho-mqtt2

      - name: Restore abuild private key
        run: |
          mkdir -p /home/builder/.abuild
          echo "${{ secrets.ABUILD_PRIVATE_KEY }}" | base64 -d \
            > /home/builder/.abuild/psec.rsa
          chmod 600 /home/builder/.abuild/psec.rsa
          chown -R builder:builder /home/builder/.abuild
          echo "PACKAGER_PRIVKEY=/home/builder/.abuild/psec.rsa" >> /etc/abuild.conf
          echo "PACKAGER_NAME=\"Tristan IsraÃ«l\"" >> /etc/abuild.conf
          echo "PACKAGER_EMAIL=\"tristan.israel@alefbet.net\"" >> /etc/abuild.conf
          echo "PACKAGER_SIGN=1" >> /etc/abuild.conf

      - name: Copy abuild public key 
        run: |
          cp certs/psec.rsa.pub /home/builder/.abuild

      - name: Build APK
        working-directory: setup/packages/psec/py3-paho-mqtt2
        run: |
          sudo -u builder abuild checksum
          sudo -u builder abuild -r